---
title: "ADNI Mixed Effect Models"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(IRISUtils)
```

# Mixed Effect Models

```{r, eval=FALSE}
wgs_adno_partitioner(
  partition_number = 300,
  clinical_variables = c("MMSE", "GENDER","AGE", "MMSE.bl", "PTEDUCAT", "PTID", "VISID"),
  pca_components = c("PC1", "PC2", "PC3"),
  wgs_path = "/data/array/mshoai/ADprogressionData/ADNI/WGScompletedQC_phenoed.raw",
  pca_path = "/data/array/mshoai/ADprogressionData/ADNI/ADNIprunedpostQCPCA.eigenvec",
  adni_path = "/data/array/mshoai/ADprogressionData/ADNI/adnimerge.RData",
  partitions_save_path = "/data/array/mshoai/ADprogressionData/ADNI/data_partitions/")
```


```{r, eval=FALSE}
function_to_Rscript(
  script_name = "/data/array/mshoai/ADprogressionData/ADNI/scripts/Parallel_Modeling.R", 
  function_from_source = NULL,
  function_name = "lmer_modeling",
  packages =  c("IRISUtils"),
  arguments = c("data_path", "simulation_name", "formula", "save_model_path"),
  arguments_class = c("character", "character", "character", "character")
)
```

```{r,eval=FALSE}
partitions_files = list.files("/data/array/mshoai/ADprogressionData/ADNI/data_partitions/", full.names = T) 
save_model_path = "/data/array/mshoai/ADprogressionData/ADNI/models/full_model/"
formula = "MMSE~GENDER+AGE+MMSE.bl+PC1+PC2+PC3+PTEDUCAT+copy_number+(1|PTID)+(1|VISID)"
parallel_rscripts(
  rscript_path = "/data/array/mshoai/ADprogressionData/ADNI/scripts/Parallel_Modeling.R",
  args = list(data_path = partitions_files, simulation_name = "full_model",
              formula = formula, save_model_path = save_model_path),
  core_numbers = 50,
  free_memory_treshold = 75,
  free_cpu_treshold = 75,
  sleep_time = 10
)
```



