---
title: "How to parrallelize R functions with HLSGUtils package?"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(HLSGUtils)
```

`~/Desktop/modeling.R`

```{r, eval=FALSE, echo=TRUE}
linear_fitter <- function(formula, n){
  df <- data.frame(
    y = rnorm(n, mean = 3),
    x1 = rnorm(n),
    x2 = rnorm(n),
    x3 = rnorm(n)
    )
  fit <- lm(as.formula(formula), data = df)
  write_rds(broom::tidy(fit),sprintf("~/Desktop/fittel_lm_%s.rds",n))
  print(sprintf("%s modeling was done with %s samples!", formula, n))
}
```

```{r, eval=FALSE, echo=TRUE}
function_to_Rscript(
  function_from_source = "~/Desktop/modeling.R",
  function_name = "linear_fitter", 
  packages = c("readr","broom"),
  arguments = c("formula","n"),
  arguments_class = c("character","integer"),
  script_save_path = "~/Desktop/modeling_r_script.R"
  )
```


```{r, eval=FALSE, echo=TRUE}
############################################################
#                      linear_fitter                       #
############################################################

args <- commandArgs(trailingOnly = TRUE)
if (length(args) < 2){stop('I think you forgot your parameters')}

formula <- args[1]
n <- as.integer(args[2])

flush.console()

# Load Libraries
suppressMessages(library(readr))
suppressMessages(library(broom))
source("~/Desktop/modeling.R")

# Add Function Its Arguments
linear_fitter(
formula = formula,
n = n
)
```

```{bash}
Rscript --vanilla ~/Desktop/modeling_r_script.R y~x1 100
```

```{r}
readr::read_rds("~/Desktop/fittel_lm_100.rds")
```


```{r, echo=TRUE, eval=FALSE}
sample_size = c(100,200,300)
formulas = c("y~x1", "y~x1+x2", "y~x1+x2+x3")
parallel_rscripts(
  rscript_path = "~/Desktop/modeling_r_script.R",
  args = list(formula = formulas, n = sample_size),
  free_memory_treshold = 80,
  free_cpu_treshold = 80,
  sleep_time = 5 )
```

